//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUCTIONonlineWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidDb
    {
        public int BidID { get; set; }
        public int SaleId { get; set; }
        public int UserId { get; set; }
        public decimal BidAmount { get; set; }
        public Nullable<bool> Successfull { get; set; }
        public Nullable<System.DateTime> BidTime { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual User User { get; set; }
    }
}
